// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/dfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_UNKNOWN   NodeState = 0
	NodeState_HEALTHY   NodeState = 1
	NodeState_UNHEALTHY NodeState = 2
	NodeState_OFFLINE   NodeState = 3
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "OFFLINE",
	}
	NodeState_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"OFFLINE":   3,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dfs_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_proto_dfs_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{0}
}

// -----------------------------
// Messages (metadata & chunks)
// -----------------------------
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // unique file identifier (UUID)
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                     // original filename
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // original file size
	Chunks        []*ChunkMeta           `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`                         // ordered chunk list
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadata) GetChunks() []*ChunkMeta {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FileMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChunkMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`        // unique chunk id
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                          // chunk index (0..n-1)
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // size of this chunk
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // e.g. sha256 hex
	NodeIds       []string               `protobuf:"bytes,5,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`        // node ids that hold this chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMeta) Reset() {
	*x = ChunkMeta{}
	mi := &file_proto_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMeta) ProtoMessage() {}

func (x *ChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMeta.ProtoReflect.Descriptor instead.
func (*ChunkMeta) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkMeta) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkMeta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ChunkMeta) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ChunkMeta) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // host:port
	State         NodeState              `protobuf:"varint,3,opt,name=state,proto3,enum=distrophile.dfs.NodeState" json:"state,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeInfo) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_UNKNOWN
}

func (x *NodeInfo) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *NodeInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

// -----------------------------
// Chunk payload messages
// -----------------------------
type ChunkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`        // coordinator assigned chunk id (optional client side)
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                          // chunk index
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                             // raw bytes for this chunk
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // length of data
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // optional checksum (e.g. sha256)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPayload) Reset() {
	*x = ChunkPayload{}
	mi := &file_proto_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPayload) ProtoMessage() {}

func (x *ChunkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPayload.ProtoReflect.Descriptor instead.
func (*ChunkPayload) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkPayload) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkPayload) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkPayload) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ChunkPayload) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ChunkUploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadResult) Reset() {
	*x = ChunkUploadResult{}
	mi := &file_proto_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadResult) ProtoMessage() {}

func (x *ChunkUploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadResult.ProtoReflect.Descriptor instead.
func (*ChunkUploadResult) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkUploadResult) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkUploadResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChunkUploadResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChunkUploadResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChunkUploadResult) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// -----------------------------
// CLI <-> Coordinator RPCs
// -----------------------------
// Upload: bidirectional streaming so client can stream chunks and receive per-chunk/summary acks.
type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either metadata (first message) OR a chunk payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Meta
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetMeta() *FileUploadMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() *ChunkPayload {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Meta struct {
	Meta *FileUploadMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk *ChunkPayload `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Meta) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type FileUploadMeta struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Filename  string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ChunkSize int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // coordinator hint (bytes)
	// Optional client-provided file_id to resume; otherwise server generates one
	FileId        string `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadMeta) Reset() {
	*x = FileUploadMeta{}
	mi := &file_proto_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadMeta) ProtoMessage() {}

func (x *FileUploadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadMeta.ProtoReflect.Descriptor instead.
func (*FileUploadMeta) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *FileUploadMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileUploadMeta) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileUploadMeta) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadResponse_ChunkResult
	//	*UploadResponse_Summary
	//	*UploadResponse_Error
	Payload       isUploadResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *UploadResponse) GetPayload() isUploadResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadResponse) GetChunkResult() *ChunkUploadResult {
	if x != nil {
		if x, ok := x.Payload.(*UploadResponse_ChunkResult); ok {
			return x.ChunkResult
		}
	}
	return nil
}

func (x *UploadResponse) GetSummary() *FileUploadSummary {
	if x != nil {
		if x, ok := x.Payload.(*UploadResponse_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *UploadResponse) GetError() *ErrorErr {
	if x != nil {
		if x, ok := x.Payload.(*UploadResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUploadResponse_Payload interface {
	isUploadResponse_Payload()
}

type UploadResponse_ChunkResult struct {
	ChunkResult *ChunkUploadResult `protobuf:"bytes,1,opt,name=chunk_result,json=chunkResult,proto3,oneof"` // ack for each chunk
}

type UploadResponse_Summary struct {
	Summary *FileUploadSummary `protobuf:"bytes,2,opt,name=summary,proto3,oneof"` // final summary returned when upload completes
}

type UploadResponse_Error struct {
	Error *ErrorErr `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*UploadResponse_ChunkResult) isUploadResponse_Payload() {}

func (*UploadResponse_Summary) isUploadResponse_Payload() {}

func (*UploadResponse_Error) isUploadResponse_Payload() {}

type FileUploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Metadata      *FileMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadSummary) Reset() {
	*x = FileUploadSummary{}
	mi := &file_proto_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadSummary) ProtoMessage() {}

func (x *FileUploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadSummary.ProtoReflect.Descriptor instead.
func (*FileUploadSummary) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *FileUploadSummary) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileUploadSummary) GetMetadata() *FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ErrorErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorErr) Reset() {
	*x = ErrorErr{}
	mi := &file_proto_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorErr) ProtoMessage() {}

func (x *ErrorErr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorErr.ProtoReflect.Descriptor instead.
func (*ErrorErr) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorErr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorErr) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Download: client sends download request, server streams chunk payloads back
type DownloadRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FileId string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// optional: allow selecting preferred node or force checksum checks etc.
	PreferredNodes []string `protobuf:"bytes,2,rep,name=preferred_nodes,json=preferredNodes,proto3" json:"preferred_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadRequest) GetPreferredNodes() []string {
	if x != nil {
		return x.PreferredNodes
	}
	return nil
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadResponse_Chunk
	//	*DownloadResponse_Metadata
	//	*DownloadResponse_Error
	Payload       isDownloadResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_proto_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadResponse) GetPayload() isDownloadResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadResponse) GetChunk() *ChunkPayload {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DownloadResponse) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownloadResponse) GetError() *ErrorErr {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDownloadResponse_Payload interface {
	isDownloadResponse_Payload()
}

type DownloadResponse_Chunk struct {
	Chunk *ChunkPayload `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type DownloadResponse_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof"` // optionally send metadata first
}

type DownloadResponse_Error struct {
	Error *ErrorErr `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*DownloadResponse_Chunk) isDownloadResponse_Payload() {}

func (*DownloadResponse_Metadata) isDownloadResponse_Payload() {}

func (*DownloadResponse_Error) isDownloadResponse_Payload() {}

// List files & nodes
type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination (optional)
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *ListFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *ListFilesResponse) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_proto_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{14}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_proto_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *GetFileInfoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// -----------------------------
// Coordinator <-> Storage Node RPCs
// -----------------------------
type StoreChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk metadata plus payload
	Chunk *ChunkPayload `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// origin metadata (file id, uploader id)
	FileId        string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Uploader      string `protobuf:"bytes,3,opt,name=uploader,proto3" json:"uploader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkRequest) Reset() {
	*x = StoreChunkRequest{}
	mi := &file_proto_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkRequest) ProtoMessage() {}

func (x *StoreChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkRequest.ProtoReflect.Descriptor instead.
func (*StoreChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{17}
}

func (x *StoreChunkRequest) GetChunk() *ChunkPayload {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *StoreChunkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StoreChunkRequest) GetUploader() string {
	if x != nil {
		return x.Uploader
	}
	return ""
}

type StoreChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkAck) Reset() {
	*x = StoreChunkAck{}
	mi := &file_proto_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkAck) ProtoMessage() {}

func (x *StoreChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkAck.ProtoReflect.Descriptor instead.
func (*StoreChunkAck) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *StoreChunkAck) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *StoreChunkAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StoreChunkAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreChunkAck) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *StoreChunkAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_proto_dfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{19}
}

func (x *GetChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type GetChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GetChunkResponse_Chunk
	//	*GetChunkResponse_Error
	Payload       isGetChunkResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_proto_dfs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{20}
}

func (x *GetChunkResponse) GetPayload() isGetChunkResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetChunkResponse) GetChunk() *ChunkPayload {
	if x != nil {
		if x, ok := x.Payload.(*GetChunkResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *GetChunkResponse) GetError() *ErrorErr {
	if x != nil {
		if x, ok := x.Payload.(*GetChunkResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetChunkResponse_Payload interface {
	isGetChunkResponse_Payload()
}

type GetChunkResponse_Chunk struct {
	Chunk *ChunkPayload `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type GetChunkResponse_Error struct {
	Error *ErrorErr `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetChunkResponse_Chunk) isGetChunkResponse_Payload() {}

func (*GetChunkResponse_Error) isGetChunkResponse_Payload() {}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional: request for additional info
	Full          bool `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_dfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *NodeInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// quick metrics
	ActiveConnections int32     `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	StorageOk         bool      `protobuf:"varint,3,opt,name=storage_ok,json=storageOk,proto3" json:"storage_ok,omitempty"`
	Error             *ErrorErr `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_dfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{22}
}

func (x *HealthCheckResponse) GetInfo() *NodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *HealthCheckResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthCheckResponse) GetStorageOk() bool {
	if x != nil {
		return x.StorageOk
	}
	return false
}

func (x *HealthCheckResponse) GetError() *ErrorErr {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReplicateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SourceNode    string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"` // optional; coordinator may provide source
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // usually the node receiving this RPC is target_node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkRequest) Reset() {
	*x = ReplicateChunkRequest{}
	mi := &file_proto_dfs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkRequest) ProtoMessage() {}

func (x *ReplicateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkRequest.ProtoReflect.Descriptor instead.
func (*ReplicateChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{23}
}

func (x *ReplicateChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicateChunkRequest) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *ReplicateChunkRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type ReplicateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkResponse) Reset() {
	*x = ReplicateChunkResponse{}
	mi := &file_proto_dfs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkResponse) ProtoMessage() {}

func (x *ReplicateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkResponse.ProtoReflect.Descriptor instead.
func (*ReplicateChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{24}
}

func (x *ReplicateChunkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReplicateChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicateChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// -----------------------------
// Replication & Jobs (Coordinator internal / optional RPCs)
// -----------------------------
type ReplicationJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	SourceNode    string                 `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	TargetNode    string                 `protobuf:"bytes,5,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Success       bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationJob) Reset() {
	*x = ReplicationJob{}
	mi := &file_proto_dfs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationJob) ProtoMessage() {}

func (x *ReplicationJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationJob.ProtoReflect.Descriptor instead.
func (*ReplicationJob) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{25}
}

func (x *ReplicationJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReplicationJob) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReplicationJob) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicationJob) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *ReplicationJob) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *ReplicationJob) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *ReplicationJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReplicationJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ReplicationJob) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationJob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplicationJobAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationJobAck) Reset() {
	*x = ReplicationJobAck{}
	mi := &file_proto_dfs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationJobAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationJobAck) ProtoMessage() {}

func (x *ReplicationJobAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationJobAck.ProtoReflect.Descriptor instead.
func (*ReplicationJobAck) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{26}
}

func (x *ReplicationJobAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReplicationJobAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReplicationJobAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListReplicationJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationJobsRequest) Reset() {
	*x = ListReplicationJobsRequest{}
	mi := &file_proto_dfs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationJobsRequest) ProtoMessage() {}

func (x *ListReplicationJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationJobsRequest.ProtoReflect.Descriptor instead.
func (*ListReplicationJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{27}
}

func (x *ListReplicationJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReplicationJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListReplicationJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ReplicationJob      `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationJobsResponse) Reset() {
	*x = ListReplicationJobsResponse{}
	mi := &file_proto_dfs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationJobsResponse) ProtoMessage() {}

func (x *ListReplicationJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationJobsResponse.ProtoReflect.Descriptor instead.
func (*ListReplicationJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{28}
}

func (x *ListReplicationJobsResponse) GetJobs() []*ReplicationJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListReplicationJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_dfs_proto protoreflect.FileDescriptor

const file_proto_dfs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/dfs.proto\x12\x0fdistrophile.dfs\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\fFileMetadata\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x122\n" +
	"\x06chunks\x18\x04 \x03(\v2\x1a.distrophile.dfs.ChunkMetaR\x06chunks\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x01\n" +
	"\tChunkMeta\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x19\n" +
	"\bnode_ids\x18\x05 \x03(\tR\anodeIds\"\xcb\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x120\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.distrophile.dfs.NodeStateR\x05state\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x03R\tfreeBytes\x12A\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\x8e\x01\n" +
	"\fChunkPayload\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"\x93\x01\n" +
	"\x11ChunkUploadResult\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"\x88\x01\n" +
	"\rUploadRequest\x125\n" +
	"\x04meta\x18\x01 \x01(\v2\x1f.distrophile.dfs.FileUploadMetaH\x00R\x04meta\x125\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1d.distrophile.dfs.ChunkPayloadH\x00R\x05chunkB\t\n" +
	"\apayload\"\x83\x01\n" +
	"\x0eFileUploadMeta\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\tR\x06fileId\"\xd7\x01\n" +
	"\x0eUploadResponse\x12G\n" +
	"\fchunk_result\x18\x01 \x01(\v2\".distrophile.dfs.ChunkUploadResultH\x00R\vchunkResult\x12>\n" +
	"\asummary\x18\x02 \x01(\v2\".distrophile.dfs.FileUploadSummaryH\x00R\asummary\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x19.distrophile.dfs.ErrorErrH\x00R\x05errorB\t\n" +
	"\apayload\"g\n" +
	"\x11FileUploadSummary\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.distrophile.dfs.FileMetadataR\bmetadata\"8\n" +
	"\bErrorErr\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"S\n" +
	"\x0fDownloadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12'\n" +
	"\x0fpreferred_nodes\x18\x02 \x03(\tR\x0epreferredNodes\"\xc4\x01\n" +
	"\x10DownloadResponse\x125\n" +
	"\x05chunk\x18\x01 \x01(\v2\x1d.distrophile.dfs.ChunkPayloadH\x00R\x05chunk\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.distrophile.dfs.FileMetadataH\x00R\bmetadata\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x19.distrophile.dfs.ErrorErrH\x00R\x05errorB\t\n" +
	"\apayload\"@\n" +
	"\x10ListFilesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"^\n" +
	"\x11ListFilesResponse\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.distrophile.dfs.FileMetadataR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x12\n" +
	"\x10ListNodesRequest\"D\n" +
	"\x11ListNodesResponse\x12/\n" +
	"\x05nodes\x18\x01 \x03(\v2\x19.distrophile.dfs.NodeInfoR\x05nodes\"-\n" +
	"\x12GetFileInfoRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"}\n" +
	"\x11StoreChunkRequest\x123\n" +
	"\x05chunk\x18\x01 \x01(\v2\x1d.distrophile.dfs.ChunkPayloadR\x05chunk\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\buploader\x18\x03 \x01(\tR\buploader\"\x85\x01\n" +
	"\rStoreChunkAck\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\",\n" +
	"\x0fGetChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x87\x01\n" +
	"\x10GetChunkResponse\x125\n" +
	"\x05chunk\x18\x01 \x01(\v2\x1d.distrophile.dfs.ChunkPayloadH\x00R\x05chunk\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.distrophile.dfs.ErrorErrH\x00R\x05errorB\t\n" +
	"\apayload\"(\n" +
	"\x12HealthCheckRequest\x12\x12\n" +
	"\x04full\x18\x01 \x01(\bR\x04full\"\xc3\x01\n" +
	"\x13HealthCheckResponse\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.distrophile.dfs.NodeInfoR\x04info\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12\x1d\n" +
	"\n" +
	"storage_ok\x18\x03 \x01(\bR\tstorageOk\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x19.distrophile.dfs.ErrorErrR\x05error\"t\n" +
	"\x15ReplicateChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\"Y\n" +
	"\x16ReplicateChunkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x82\x03\n" +
	"\x0eReplicationJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\x12\x1f\n" +
	"\vtarget_node\x18\x05 \x01(\tR\n" +
	"targetNode\x12;\n" +
	"\venqueued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\\\n" +
	"\x11ReplicationJobAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"J\n" +
	"\x1aListReplicationJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"h\n" +
	"\x1bListReplicationJobsResponse\x123\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1f.distrophile.dfs.ReplicationJobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*A\n" +
	"\tNodeState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x032\xb1\x03\n" +
	"\x12CoordinatorService\x12M\n" +
	"\x06Upload\x12\x1e.distrophile.dfs.UploadRequest\x1a\x1f.distrophile.dfs.UploadResponse(\x010\x01\x12Q\n" +
	"\bDownload\x12 .distrophile.dfs.DownloadRequest\x1a!.distrophile.dfs.DownloadResponse0\x01\x12R\n" +
	"\tListFiles\x12!.distrophile.dfs.ListFilesRequest\x1a\".distrophile.dfs.ListFilesResponse\x12R\n" +
	"\tListNodes\x12!.distrophile.dfs.ListNodesRequest\x1a\".distrophile.dfs.ListNodesResponse\x12Q\n" +
	"\vGetFileInfo\x12#.distrophile.dfs.GetFileInfoRequest\x1a\x1d.distrophile.dfs.FileMetadata2\xf8\x02\n" +
	"\x12StorageNodeService\x12T\n" +
	"\n" +
	"StoreChunk\x12\".distrophile.dfs.StoreChunkRequest\x1a\x1e.distrophile.dfs.StoreChunkAck(\x010\x01\x12O\n" +
	"\bGetChunk\x12 .distrophile.dfs.GetChunkRequest\x1a!.distrophile.dfs.GetChunkResponse\x12X\n" +
	"\vHealthCheck\x12#.distrophile.dfs.HealthCheckRequest\x1a$.distrophile.dfs.HealthCheckResponse\x12a\n" +
	"\x0eReplicateChunk\x12&.distrophile.dfs.ReplicateChunkRequest\x1a'.distrophile.dfs.ReplicateChunkResponse2\xdf\x01\n" +
	"\x10CoordinatorAdmin\x12Y\n" +
	"\x12EnqueueReplication\x12\x1f.distrophile.dfs.ReplicationJob\x1a\".distrophile.dfs.ReplicationJobAck\x12p\n" +
	"\x13ListReplicationJobs\x12+.distrophile.dfs.ListReplicationJobsRequest\x1a,.distrophile.dfs.ListReplicationJobsResponseB,Z*github.com/iLaxios/distrophile/proto;protob\x06proto3"

var (
	file_proto_dfs_proto_rawDescOnce sync.Once
	file_proto_dfs_proto_rawDescData []byte
)

func file_proto_dfs_proto_rawDescGZIP() []byte {
	file_proto_dfs_proto_rawDescOnce.Do(func() {
		file_proto_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dfs_proto_rawDesc), len(file_proto_dfs_proto_rawDesc)))
	})
	return file_proto_dfs_proto_rawDescData
}

var file_proto_dfs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_dfs_proto_goTypes = []any{
	(NodeState)(0),                      // 0: distrophile.dfs.NodeState
	(*FileMetadata)(nil),                // 1: distrophile.dfs.FileMetadata
	(*ChunkMeta)(nil),                   // 2: distrophile.dfs.ChunkMeta
	(*NodeInfo)(nil),                    // 3: distrophile.dfs.NodeInfo
	(*ChunkPayload)(nil),                // 4: distrophile.dfs.ChunkPayload
	(*ChunkUploadResult)(nil),           // 5: distrophile.dfs.ChunkUploadResult
	(*UploadRequest)(nil),               // 6: distrophile.dfs.UploadRequest
	(*FileUploadMeta)(nil),              // 7: distrophile.dfs.FileUploadMeta
	(*UploadResponse)(nil),              // 8: distrophile.dfs.UploadResponse
	(*FileUploadSummary)(nil),           // 9: distrophile.dfs.FileUploadSummary
	(*ErrorErr)(nil),                    // 10: distrophile.dfs.ErrorErr
	(*DownloadRequest)(nil),             // 11: distrophile.dfs.DownloadRequest
	(*DownloadResponse)(nil),            // 12: distrophile.dfs.DownloadResponse
	(*ListFilesRequest)(nil),            // 13: distrophile.dfs.ListFilesRequest
	(*ListFilesResponse)(nil),           // 14: distrophile.dfs.ListFilesResponse
	(*ListNodesRequest)(nil),            // 15: distrophile.dfs.ListNodesRequest
	(*ListNodesResponse)(nil),           // 16: distrophile.dfs.ListNodesResponse
	(*GetFileInfoRequest)(nil),          // 17: distrophile.dfs.GetFileInfoRequest
	(*StoreChunkRequest)(nil),           // 18: distrophile.dfs.StoreChunkRequest
	(*StoreChunkAck)(nil),               // 19: distrophile.dfs.StoreChunkAck
	(*GetChunkRequest)(nil),             // 20: distrophile.dfs.GetChunkRequest
	(*GetChunkResponse)(nil),            // 21: distrophile.dfs.GetChunkResponse
	(*HealthCheckRequest)(nil),          // 22: distrophile.dfs.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 23: distrophile.dfs.HealthCheckResponse
	(*ReplicateChunkRequest)(nil),       // 24: distrophile.dfs.ReplicateChunkRequest
	(*ReplicateChunkResponse)(nil),      // 25: distrophile.dfs.ReplicateChunkResponse
	(*ReplicationJob)(nil),              // 26: distrophile.dfs.ReplicationJob
	(*ReplicationJobAck)(nil),           // 27: distrophile.dfs.ReplicationJobAck
	(*ListReplicationJobsRequest)(nil),  // 28: distrophile.dfs.ListReplicationJobsRequest
	(*ListReplicationJobsResponse)(nil), // 29: distrophile.dfs.ListReplicationJobsResponse
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
}
var file_proto_dfs_proto_depIdxs = []int32{
	2,  // 0: distrophile.dfs.FileMetadata.chunks:type_name -> distrophile.dfs.ChunkMeta
	30, // 1: distrophile.dfs.FileMetadata.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: distrophile.dfs.FileMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: distrophile.dfs.NodeInfo.state:type_name -> distrophile.dfs.NodeState
	30, // 4: distrophile.dfs.NodeInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	7,  // 5: distrophile.dfs.UploadRequest.meta:type_name -> distrophile.dfs.FileUploadMeta
	4,  // 6: distrophile.dfs.UploadRequest.chunk:type_name -> distrophile.dfs.ChunkPayload
	5,  // 7: distrophile.dfs.UploadResponse.chunk_result:type_name -> distrophile.dfs.ChunkUploadResult
	9,  // 8: distrophile.dfs.UploadResponse.summary:type_name -> distrophile.dfs.FileUploadSummary
	10, // 9: distrophile.dfs.UploadResponse.error:type_name -> distrophile.dfs.ErrorErr
	1,  // 10: distrophile.dfs.FileUploadSummary.metadata:type_name -> distrophile.dfs.FileMetadata
	4,  // 11: distrophile.dfs.DownloadResponse.chunk:type_name -> distrophile.dfs.ChunkPayload
	1,  // 12: distrophile.dfs.DownloadResponse.metadata:type_name -> distrophile.dfs.FileMetadata
	10, // 13: distrophile.dfs.DownloadResponse.error:type_name -> distrophile.dfs.ErrorErr
	1,  // 14: distrophile.dfs.ListFilesResponse.files:type_name -> distrophile.dfs.FileMetadata
	3,  // 15: distrophile.dfs.ListNodesResponse.nodes:type_name -> distrophile.dfs.NodeInfo
	4,  // 16: distrophile.dfs.StoreChunkRequest.chunk:type_name -> distrophile.dfs.ChunkPayload
	4,  // 17: distrophile.dfs.GetChunkResponse.chunk:type_name -> distrophile.dfs.ChunkPayload
	10, // 18: distrophile.dfs.GetChunkResponse.error:type_name -> distrophile.dfs.ErrorErr
	3,  // 19: distrophile.dfs.HealthCheckResponse.info:type_name -> distrophile.dfs.NodeInfo
	10, // 20: distrophile.dfs.HealthCheckResponse.error:type_name -> distrophile.dfs.ErrorErr
	30, // 21: distrophile.dfs.ReplicationJob.enqueued_at:type_name -> google.protobuf.Timestamp
	30, // 22: distrophile.dfs.ReplicationJob.started_at:type_name -> google.protobuf.Timestamp
	30, // 23: distrophile.dfs.ReplicationJob.finished_at:type_name -> google.protobuf.Timestamp
	26, // 24: distrophile.dfs.ListReplicationJobsResponse.jobs:type_name -> distrophile.dfs.ReplicationJob
	6,  // 25: distrophile.dfs.CoordinatorService.Upload:input_type -> distrophile.dfs.UploadRequest
	11, // 26: distrophile.dfs.CoordinatorService.Download:input_type -> distrophile.dfs.DownloadRequest
	13, // 27: distrophile.dfs.CoordinatorService.ListFiles:input_type -> distrophile.dfs.ListFilesRequest
	15, // 28: distrophile.dfs.CoordinatorService.ListNodes:input_type -> distrophile.dfs.ListNodesRequest
	17, // 29: distrophile.dfs.CoordinatorService.GetFileInfo:input_type -> distrophile.dfs.GetFileInfoRequest
	18, // 30: distrophile.dfs.StorageNodeService.StoreChunk:input_type -> distrophile.dfs.StoreChunkRequest
	20, // 31: distrophile.dfs.StorageNodeService.GetChunk:input_type -> distrophile.dfs.GetChunkRequest
	22, // 32: distrophile.dfs.StorageNodeService.HealthCheck:input_type -> distrophile.dfs.HealthCheckRequest
	24, // 33: distrophile.dfs.StorageNodeService.ReplicateChunk:input_type -> distrophile.dfs.ReplicateChunkRequest
	26, // 34: distrophile.dfs.CoordinatorAdmin.EnqueueReplication:input_type -> distrophile.dfs.ReplicationJob
	28, // 35: distrophile.dfs.CoordinatorAdmin.ListReplicationJobs:input_type -> distrophile.dfs.ListReplicationJobsRequest
	8,  // 36: distrophile.dfs.CoordinatorService.Upload:output_type -> distrophile.dfs.UploadResponse
	12, // 37: distrophile.dfs.CoordinatorService.Download:output_type -> distrophile.dfs.DownloadResponse
	14, // 38: distrophile.dfs.CoordinatorService.ListFiles:output_type -> distrophile.dfs.ListFilesResponse
	16, // 39: distrophile.dfs.CoordinatorService.ListNodes:output_type -> distrophile.dfs.ListNodesResponse
	1,  // 40: distrophile.dfs.CoordinatorService.GetFileInfo:output_type -> distrophile.dfs.FileMetadata
	19, // 41: distrophile.dfs.StorageNodeService.StoreChunk:output_type -> distrophile.dfs.StoreChunkAck
	21, // 42: distrophile.dfs.StorageNodeService.GetChunk:output_type -> distrophile.dfs.GetChunkResponse
	23, // 43: distrophile.dfs.StorageNodeService.HealthCheck:output_type -> distrophile.dfs.HealthCheckResponse
	25, // 44: distrophile.dfs.StorageNodeService.ReplicateChunk:output_type -> distrophile.dfs.ReplicateChunkResponse
	27, // 45: distrophile.dfs.CoordinatorAdmin.EnqueueReplication:output_type -> distrophile.dfs.ReplicationJobAck
	29, // 46: distrophile.dfs.CoordinatorAdmin.ListReplicationJobs:output_type -> distrophile.dfs.ListReplicationJobsResponse
	36, // [36:47] is the sub-list for method output_type
	25, // [25:36] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_dfs_proto_init() }
func file_proto_dfs_proto_init() {
	if File_proto_dfs_proto != nil {
		return
	}
	file_proto_dfs_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadRequest_Meta)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	file_proto_dfs_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadResponse_ChunkResult)(nil),
		(*UploadResponse_Summary)(nil),
		(*UploadResponse_Error)(nil),
	}
	file_proto_dfs_proto_msgTypes[11].OneofWrappers = []any{
		(*DownloadResponse_Chunk)(nil),
		(*DownloadResponse_Metadata)(nil),
		(*DownloadResponse_Error)(nil),
	}
	file_proto_dfs_proto_msgTypes[20].OneofWrappers = []any{
		(*GetChunkResponse_Chunk)(nil),
		(*GetChunkResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dfs_proto_rawDesc), len(file_proto_dfs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_dfs_proto_goTypes,
		DependencyIndexes: file_proto_dfs_proto_depIdxs,
		EnumInfos:         file_proto_dfs_proto_enumTypes,
		MessageInfos:      file_proto_dfs_proto_msgTypes,
	}.Build()
	File_proto_dfs_proto = out.File
	file_proto_dfs_proto_goTypes = nil
	file_proto_dfs_proto_depIdxs = nil
}
