// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/dfs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_Upload_FullMethodName      = "/distrophile.dfs.CoordinatorService/Upload"
	CoordinatorService_Download_FullMethodName    = "/distrophile.dfs.CoordinatorService/Download"
	CoordinatorService_ListFiles_FullMethodName   = "/distrophile.dfs.CoordinatorService/ListFiles"
	CoordinatorService_ListNodes_FullMethodName   = "/distrophile.dfs.CoordinatorService/ListNodes"
	CoordinatorService_GetFileInfo_FullMethodName = "/distrophile.dfs.CoordinatorService/GetFileInfo"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLI service
type CoordinatorServiceClient interface {
	// Bidirectional streaming upload
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadRequest, UploadResponse], error)
	// Download: client sends single request, server streams DownloadResponse
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error)
	// List files
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// List nodes
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Get file metadata
	GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*FileMetadata, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[0], CoordinatorService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_UploadClient = grpc.BidiStreamingClient[UploadRequest, UploadResponse]

func (c *coordinatorServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[1], CoordinatorService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_DownloadClient = grpc.ServerStreamingClient[DownloadResponse]

func (c *coordinatorServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*FileMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileMetadata)
	err := c.cc.Invoke(ctx, CoordinatorService_GetFileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
//
// CLI service
type CoordinatorServiceServer interface {
	// Bidirectional streaming upload
	Upload(grpc.BidiStreamingServer[UploadRequest, UploadResponse]) error
	// Download: client sends single request, server streams DownloadResponse
	Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error
	// List files
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// List nodes
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Get file metadata
	GetFileInfo(context.Context, *GetFileInfoRequest) (*FileMetadata, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) Upload(grpc.BidiStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedCoordinatorServiceServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedCoordinatorServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedCoordinatorServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetFileInfo(context.Context, *GetFileInfoRequest) (*FileMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileInfo not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServiceServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_UploadServer = grpc.BidiStreamingServer[UploadRequest, UploadResponse]

func _CoordinatorService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServiceServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_DownloadServer = grpc.ServerStreamingServer[DownloadResponse]

func _CoordinatorService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetFileInfo(ctx, req.(*GetFileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrophile.dfs.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _CoordinatorService_ListFiles_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _CoordinatorService_ListNodes_Handler,
		},
		{
			MethodName: "GetFileInfo",
			Handler:    _CoordinatorService_GetFileInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _CoordinatorService_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _CoordinatorService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/dfs.proto",
}

const (
	StorageNodeService_StoreChunk_FullMethodName     = "/distrophile.dfs.StorageNodeService/StoreChunk"
	StorageNodeService_GetChunk_FullMethodName       = "/distrophile.dfs.StorageNodeService/GetChunk"
	StorageNodeService_HealthCheck_FullMethodName    = "/distrophile.dfs.StorageNodeService/HealthCheck"
	StorageNodeService_ReplicateChunk_FullMethodName = "/distrophile.dfs.StorageNodeService/ReplicateChunk"
)

// StorageNodeServiceClient is the client API for StorageNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Make StoreChunk bidirectional to allow coordinator to stream many chunks and the node ack as they come
type StorageNodeServiceClient interface {
	// Coordinator streams chunks to node; node acks back per chunk
	StoreChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StoreChunkRequest, StoreChunkAck], error)
	// Coordinator requests a chunk back
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error)
	// Node health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Instruct node to replicate a chunk from another node (coordinator-driven)
	ReplicateChunk(ctx context.Context, in *ReplicateChunkRequest, opts ...grpc.CallOption) (*ReplicateChunkResponse, error)
}

type storageNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeServiceClient(cc grpc.ClientConnInterface) StorageNodeServiceClient {
	return &storageNodeServiceClient{cc}
}

func (c *storageNodeServiceClient) StoreChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StoreChunkRequest, StoreChunkAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNodeService_ServiceDesc.Streams[0], StorageNodeService_StoreChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreChunkRequest, StoreChunkAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNodeService_StoreChunkClient = grpc.BidiStreamingClient[StoreChunkRequest, StoreChunkAck]

func (c *storageNodeServiceClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkResponse)
	err := c.cc.Invoke(ctx, StorageNodeService_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, StorageNodeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeServiceClient) ReplicateChunk(ctx context.Context, in *ReplicateChunkRequest, opts ...grpc.CallOption) (*ReplicateChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateChunkResponse)
	err := c.cc.Invoke(ctx, StorageNodeService_ReplicateChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServiceServer is the server API for StorageNodeService service.
// All implementations must embed UnimplementedStorageNodeServiceServer
// for forward compatibility.
//
// Make StoreChunk bidirectional to allow coordinator to stream many chunks and the node ack as they come
type StorageNodeServiceServer interface {
	// Coordinator streams chunks to node; node acks back per chunk
	StoreChunk(grpc.BidiStreamingServer[StoreChunkRequest, StoreChunkAck]) error
	// Coordinator requests a chunk back
	GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error)
	// Node health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Instruct node to replicate a chunk from another node (coordinator-driven)
	ReplicateChunk(context.Context, *ReplicateChunkRequest) (*ReplicateChunkResponse, error)
	mustEmbedUnimplementedStorageNodeServiceServer()
}

// UnimplementedStorageNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServiceServer struct{}

func (UnimplementedStorageNodeServiceServer) StoreChunk(grpc.BidiStreamingServer[StoreChunkRequest, StoreChunkAck]) error {
	return status.Errorf(codes.Unimplemented, "method StoreChunk not implemented")
}
func (UnimplementedStorageNodeServiceServer) GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedStorageNodeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStorageNodeServiceServer) ReplicateChunk(context.Context, *ReplicateChunkRequest) (*ReplicateChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateChunk not implemented")
}
func (UnimplementedStorageNodeServiceServer) mustEmbedUnimplementedStorageNodeServiceServer() {}
func (UnimplementedStorageNodeServiceServer) testEmbeddedByValue()                            {}

// UnsafeStorageNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServiceServer will
// result in compilation errors.
type UnsafeStorageNodeServiceServer interface {
	mustEmbedUnimplementedStorageNodeServiceServer()
}

func RegisterStorageNodeServiceServer(s grpc.ServiceRegistrar, srv StorageNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNodeService_ServiceDesc, srv)
}

func _StorageNodeService_StoreChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageNodeServiceServer).StoreChunk(&grpc.GenericServerStream[StoreChunkRequest, StoreChunkAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNodeService_StoreChunkServer = grpc.BidiStreamingServer[StoreChunkRequest, StoreChunkAck]

func _StorageNodeService_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServiceServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNodeService_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServiceServer).GetChunk(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNodeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNodeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNodeService_ReplicateChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServiceServer).ReplicateChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNodeService_ReplicateChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServiceServer).ReplicateChunk(ctx, req.(*ReplicateChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNodeService_ServiceDesc is the grpc.ServiceDesc for StorageNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrophile.dfs.StorageNodeService",
	HandlerType: (*StorageNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChunk",
			Handler:    _StorageNodeService_GetChunk_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _StorageNodeService_HealthCheck_Handler,
		},
		{
			MethodName: "ReplicateChunk",
			Handler:    _StorageNodeService_ReplicateChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreChunk",
			Handler:       _StorageNodeService_StoreChunk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dfs.proto",
}

const (
	CoordinatorAdmin_EnqueueReplication_FullMethodName  = "/distrophile.dfs.CoordinatorAdmin/EnqueueReplication"
	CoordinatorAdmin_ListReplicationJobs_FullMethodName = "/distrophile.dfs.CoordinatorAdmin/ListReplicationJobs"
)

// CoordinatorAdminClient is the client API for CoordinatorAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorAdminClient interface {
	EnqueueReplication(ctx context.Context, in *ReplicationJob, opts ...grpc.CallOption) (*ReplicationJobAck, error)
	ListReplicationJobs(ctx context.Context, in *ListReplicationJobsRequest, opts ...grpc.CallOption) (*ListReplicationJobsResponse, error)
}

type coordinatorAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorAdminClient(cc grpc.ClientConnInterface) CoordinatorAdminClient {
	return &coordinatorAdminClient{cc}
}

func (c *coordinatorAdminClient) EnqueueReplication(ctx context.Context, in *ReplicationJob, opts ...grpc.CallOption) (*ReplicationJobAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationJobAck)
	err := c.cc.Invoke(ctx, CoordinatorAdmin_EnqueueReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorAdminClient) ListReplicationJobs(ctx context.Context, in *ListReplicationJobsRequest, opts ...grpc.CallOption) (*ListReplicationJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplicationJobsResponse)
	err := c.cc.Invoke(ctx, CoordinatorAdmin_ListReplicationJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorAdminServer is the server API for CoordinatorAdmin service.
// All implementations must embed UnimplementedCoordinatorAdminServer
// for forward compatibility.
type CoordinatorAdminServer interface {
	EnqueueReplication(context.Context, *ReplicationJob) (*ReplicationJobAck, error)
	ListReplicationJobs(context.Context, *ListReplicationJobsRequest) (*ListReplicationJobsResponse, error)
	mustEmbedUnimplementedCoordinatorAdminServer()
}

// UnimplementedCoordinatorAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorAdminServer struct{}

func (UnimplementedCoordinatorAdminServer) EnqueueReplication(context.Context, *ReplicationJob) (*ReplicationJobAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueReplication not implemented")
}
func (UnimplementedCoordinatorAdminServer) ListReplicationJobs(context.Context, *ListReplicationJobsRequest) (*ListReplicationJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReplicationJobs not implemented")
}
func (UnimplementedCoordinatorAdminServer) mustEmbedUnimplementedCoordinatorAdminServer() {}
func (UnimplementedCoordinatorAdminServer) testEmbeddedByValue()                          {}

// UnsafeCoordinatorAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorAdminServer will
// result in compilation errors.
type UnsafeCoordinatorAdminServer interface {
	mustEmbedUnimplementedCoordinatorAdminServer()
}

func RegisterCoordinatorAdminServer(s grpc.ServiceRegistrar, srv CoordinatorAdminServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorAdmin_ServiceDesc, srv)
}

func _CoordinatorAdmin_EnqueueReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorAdminServer).EnqueueReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorAdmin_EnqueueReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorAdminServer).EnqueueReplication(ctx, req.(*ReplicationJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorAdmin_ListReplicationJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicationJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorAdminServer).ListReplicationJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorAdmin_ListReplicationJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorAdminServer).ListReplicationJobs(ctx, req.(*ListReplicationJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorAdmin_ServiceDesc is the grpc.ServiceDesc for CoordinatorAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrophile.dfs.CoordinatorAdmin",
	HandlerType: (*CoordinatorAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueReplication",
			Handler:    _CoordinatorAdmin_EnqueueReplication_Handler,
		},
		{
			MethodName: "ListReplicationJobs",
			Handler:    _CoordinatorAdmin_ListReplicationJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dfs.proto",
}
